development:
  adapter: postgresql
  encoding: unicode
  database: ot_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ot_production
  pool: 5
  username: postgres
  password: